-- 1. Create the Customers Table
CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY,
    Email VARCHAR(100),
    Status VARCHAR(20)
);

-- 2. Create the Products Table
CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100),
    Price DECIMAL(10,2)
);

-- 3. Create the Orders Table
CREATE TABLE Orders (
    OrderID INT PRIMARY KEY,
    CustomerID INT,
    ProductID INT,
    OrderDate DATE,
    OrderStatus VARCHAR(20)
);

-- 4. Inject QA Data (Customers)
INSERT INTO Customers (CustomerID, Email, Status) VALUES (1, 'active.buyer@test.com', 'Active');
INSERT INTO Customers (CustomerID, Email, Status) VALUES (2, 'no.purchases@test.com', 'Active');
INSERT INTO Customers (CustomerID, Email, Status) VALUES (3, 'banned.user@test.com', 'Suspended');

-- 5. Inject QA Data (Products)
INSERT INTO Products (ProductID, ProductName, Price) VALUES (101, 'Pro Software License', 299.99);
INSERT INTO Products (ProductID, ProductName, Price) VALUES (102, 'Basic Subscription', 15.00);

-- 6. Inject QA Data (Orders)
INSERT INTO Orders (OrderID, CustomerID, ProductID, OrderDate, OrderStatus) VALUES (5001, 1, 101, '2026-07-01', 'Completed');
INSERT INTO Orders (OrderID, CustomerID, ProductID, OrderDate, OrderStatus) VALUES (5002, 1, 102, '2026-07-02', 'Completed');
INSERT INTO Orders (OrderID, CustomerID, ProductID, OrderDate, OrderStatus) VALUES (5003, 3, 101, '2026-07-03', 'Failed');

/* QA CHECK 1: The Orphan Record Hunt (LEFT JOIN)
   Objective: Find active customers who have registered but have zero orders in the system. */
SELECT c.CustomerID, c.Email
FROM Customers c
LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
WHERE o.OrderID IS NULL AND c.Status = 'Active';

/* QA CHECK 2: Financial Math Validation (SUM & GROUP BY)
   Objective: Calculate the total revenue generated by a specific customer to verify frontend dashboard totals. */
SELECT c.Email, SUM(p.Price) AS Total_Spent
FROM Customers c
INNER JOIN Orders o ON c.CustomerID = o.CustomerID
INNER JOIN Products p ON o.ProductID = p.ProductID
WHERE o.OrderStatus = 'Completed'
GROUP BY c.Email;

/* QA CHECK 3: Security / Logic Validation
   Objective: Ensure suspended users do not have any 'Completed' orders after their suspension date. */
SELECT o.OrderID, c.Email, o.OrderStatus
FROM Orders o
INNER JOIN Customers c ON o.CustomerID = c.CustomerID
WHERE c.Status = 'Suspended' AND o.OrderStatus = 'Completed';

-- Performance Optimization: Indexing columns heavily utilized in lookups
CREATE INDEX idx_orders_customer_status ON Orders(CustomerID, OrderStatus);

-- Performance Validation Check
EXPLAIN ANALYZE
SELECT c.Email, o.OrderID 
FROM Customers c 
INNER JOIN Orders o ON c.CustomerID = o.CustomerID 
WHERE o.OrderStatus = 'Completed';
